name: PR Check

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter

      - name: flutter analyze
        run: flutter analyze

      - name: flutter test
        run: flutter test --coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report
          path: coverage/
          retention-days: 7
